# 개발환경 설정 (SQLite)
spring:
  datasource:
    url: jdbc:sqlite:./data/shoplite.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

logging:
  level:
    com.shoplite: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 개발환경 메시지
info:
  app:
    name: ShopLite Backend
    environment: Development
    database: SQLite
    description: 로컬 개발환경 - SQLite 파일 기반 데이터베이스 사용



